apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
  labels:
    app: jupyterhub
    lab: "4"
spec:
  type: NodePort
  selector:
    app: jupyterhub
  ports:
    - port: 8000
      targetPort: 8000